#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Bidvalet.Droid.Resource", IsApplication=true)]

namespace Bidvalet.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010002
			public const int background = 2130771970;
			
			// aapt resource value: 0x7F010000
			public const int BidProgressBackground = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int BidRed = 2130771969;
			
			// aapt resource value: 0x7F010003
			public const int black = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int blue = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int blue_dark = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int blue_extra_dark = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int blue_extra_light = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int blue_light = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int blue_medium = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int blue_new_kid = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int borderExpired = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int colorAccent = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int colorBidEmail = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int colorBidPrint = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int colorButtonGreen = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int colorButtonRed = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int colorExpired = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int colorGreenHomeDateTitle = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int colorHomeButton = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int colorPrimary = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int colorPrimaryDark = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int colorRedHomeDateTitle = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int colorRowGreen = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int colorSelectBase = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int colorSelectSeat = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public const int colorSort = 2130771994;
			
			// aapt resource value: 0x7F01001B
			public const int dark_divider = 2130771995;
			
			// aapt resource value: 0x7F01001C
			public const int gray_background = 2130771996;
			
			// aapt resource value: 0x7F01001D
			public const int green = 2130771997;
			
			// aapt resource value: 0x7F01001E
			public const int grey_dark = 2130771998;
			
			// aapt resource value: 0x7F01001F
			public const int grey_extra_dark = 2130771999;
			
			// aapt resource value: 0x7F010020
			public const int grey_extra_light = 2130772000;
			
			// aapt resource value: 0x7F010021
			public const int grey_light = 2130772001;
			
			// aapt resource value: 0x7F010022
			public const int grey_medium = 2130772002;
			
			// aapt resource value: 0x7F010023
			public const int grey_medium_dark = 2130772003;
			
			// aapt resource value: 0x7F010024
			public const int grey_medium_light = 2130772004;
			
			// aapt resource value: 0x7F010025
			public const int orange_dark = 2130772005;
			
			// aapt resource value: 0x7F010026
			public const int orange_medium = 2130772006;
			
			// aapt resource value: 0x7F010027
			public const int orange_red = 2130772007;
			
			// aapt resource value: 0x7F010028
			public const int primaryColor_500 = 2130772008;
			
			// aapt resource value: 0x7F010029
			public const int primaryDarkColor_700 = 2130772009;
			
			// aapt resource value: 0x7F01002A
			public const int red = 2130772010;
			
			// aapt resource value: 0x7F01002B
			public const int translucent = 2130772011;
			
			// aapt resource value: 0x7F01002C
			public const int transparent = 2130772012;
			
			// aapt resource value: 0x7F01002D
			public const int white = 2130772013;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int d_20px = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int height_100dp = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int height_110dp = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int height_115dp = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int height_120dp = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int height_150dp = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int height_1dp = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int height_20dp = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int height_220dp = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int height_2dp = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int height_30dp = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int height_40dp = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int height_50dp = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int height_5dp = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int height_60dp = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int height_70dp = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int height_80dp = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int height_90dp = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int p10dp = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int p15dp = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int p20dp = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int p30dp = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int p40dp = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int p4dp = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int p5dp = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int p8dp = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int text_sz_10sp = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int text_sz_11sp = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int text_sz_12sp = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int text_sz_13sp = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int text_sz_14sp = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int text_sz_15sp = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int text_sz_16sp = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int text_sz_17sp = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int text_sz_18sp = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int text_sz_20sp = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int text_sz_22sp = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int text_sz_25sp = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int text_sz_28sp = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int text_sz_40sp = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int text_sz_8sp = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int width_120dp = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int width_150dp = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int width_180dp = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int width_240dp = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int width_30dp = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int width_320dp = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int width_40dp = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int width_480dp = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int width_60dp = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int width_80dp = 2130837554;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030002
			public const int bidvalet_background_row = 2130903042;
			
			// aapt resource value: 0x7F03000B
			public const int bidvalet_buttoncolors = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int bidvalet_buttonpressed = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int bidvalet_buttonstates = 2130903053;
			
			// aapt resource value: 0x7F030003
			public const int bidvalet_button_block_normal = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int bidvalet_button_block_pressed = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int bidvalet_button_fitart_normal = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int bidvalet_button_fitart_pressed = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int bidvalet_button_pilot_normal = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int bidvalet_button_pilot_pressed = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int bidvalet_button_standard_normal = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int bidvalet_button_standard_pressed = 2130903050;
			
			// aapt resource value: 0x7F03000E
			public const int bidvalet_cancel_roundedbutton = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int bidvalet_commute_black = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int bidvalet_create_roundedbutton = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int bidvalet_done_setting_commute = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int bidvalet_email_roundedbutton = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int bidvalet_expired_roundedbutton = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int bidvalet_gray_border_button = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int bidvalet_gray_border_oval = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int bidvalet_green_border_button = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int bidvalet_green_border_oval = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int bidvalet_homestart_roundedbutton = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int bidvalet_login_roundededittext = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int bidvalet_off_border_button = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int bidvalet_print_roundedbutton = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int bidvalet_red_border_oval = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int bidvalet_roundedbutton = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int bidvalet_selector_fitart_button = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int bidvalet_selector_pilot_button = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int bidvalet_setcarrier_roundedbutton = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int bidvalet_sort_roundedbutton = 2130903073;
			
			// aapt resource value: 0x7F030022
			public const int bidvalet_submital_green_rectangebutton = 2130903074;
			
			// aapt resource value: 0x7F030023
			public const int bidvalet_submital_orange_rectangebutton = 2130903075;
			
			// aapt resource value: 0x7F030024
			public const int bidvalet_view_commute_time = 2130903076;
			
			// aapt resource value: 0x7F030025
			public const int bidvalet_white_border_button = 2130903077;
			
			// aapt resource value: 0x7F030026
			public const int bidvalet_white_border_oval = 2130903078;
			
			// aapt resource value: 0x7F030027
			public const int bidvalet_work_border_button = 2130903079;
			
			// aapt resource value: 0x7F030001
			public const int bid_progress_background = 2130903041;
			
			// aapt resource value: 0x7F030028
			public const int delete = 2130903080;
			
			// aapt resource value: 0x7F030000
			public const int Icon = 2130903040;
			
			// aapt resource value: 0x7F030029
			public const int icon_arrow_left = 2130903081;
			
			// aapt resource value: 0x7F03002A
			public const int icon_arrow_right = 2130903082;
			
			// aapt resource value: 0x7F03002B
			public const int icon_menu = 2130903083;
			
			// aapt resource value: 0x7F03002C
			public const int icon_minus = 2130903084;
			
			// aapt resource value: 0x7F03002D
			public const int icon_plus = 2130903085;
			
			// aapt resource value: 0x7F03002E
			public const int icon_small_menu = 2130903086;
			
			// aapt resource value: 0x7F03002F
			public const int info = 2130903087;
			
			// aapt resource value: 0x7F030030
			public const int rainDrops = 2130903088;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040004
			public const int accept_email_switch = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int accept_term_switch = 2130968581;
			
			// aapt resource value: 0x7F040000
			public const int AppNameView = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int BackButton = 2130968577;
			
			// aapt resource value: 0x7F040006
			public const int background = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int btnAdvancePay = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int btnAdvancePayBlock = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int btnAdvancePayDay = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int btnAdvancePayDutty = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int btnAdvancePayFDP = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int btnAdvancePayTAFB = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int btnAll = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int btnAny = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int btnBlank = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int btnBlock = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int btnBlockAMPM = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int btnBlockDayOff = 2130968594;
			
			// aapt resource value: 0x7F040014
			public const int btnBlockPay = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int btnBlockPayDutty = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int btnBlockPerDiem = 2130968598;
			
			// aapt resource value: 0x7F040013
			public const int btnBlockPMAM = 2130968595;
			
			// aapt resource value: 0x7F040017
			public const int btnBlockSort = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int btnBlockVacPay = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int btnBlockWeekday = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int btnBoth = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public const int btnCalculate = 2130968603;
			
			// aapt resource value: 0x7F04001C
			public const int btnCancel = 2130968604;
			
			// aapt resource value: 0x7F04001D
			public const int btnCellAm = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public const int btnCellMix = 2130968606;
			
			// aapt resource value: 0x7F04001F
			public const int btnCellPm = 2130968607;
			
			// aapt resource value: 0x7F040020
			public const int btnClear = 2130968608;
			
			// aapt resource value: 0x7F040021
			public const int btnClearAll = 2130968609;
			
			// aapt resource value: 0x7F040022
			public const int btnContinue = 2130968610;
			
			// aapt resource value: 0x7F040023
			public const int btnDelete = 2130968611;
			
			// aapt resource value: 0x7F040024
			public const int btnDone = 2130968612;
			
			// aapt resource value: 0x7F040025
			public const int btnDrag = 2130968613;
			
			// aapt resource value: 0x7F040026
			public const int btnEditAccount = 2130968614;
			
			// aapt resource value: 0x7F040027
			public const int btnEmail = 2130968615;
			
			// aapt resource value: 0x7F040028
			public const int btnExpired = 2130968616;
			
			// aapt resource value: 0x7F040029
			public const int btnExpiredSubscription = 2130968617;
			
			// aapt resource value: 0x7F04002A
			public const int btnFitArt = 2130968618;
			
			// aapt resource value: 0x7F04002B
			public const int btnFoDay = 2130968619;
			
			// aapt resource value: 0x7F04002C
			public const int btnFr = 2130968620;
			
			// aapt resource value: 0x7F04002D
			public const int btnHard = 2130968621;
			
			// aapt resource value: 0x7F04002E
			public const int btnInt = 2130968622;
			
			// aapt resource value: 0x7F04002F
			public const int btnLineThenPosition = 2130968623;
			
			// aapt resource value: 0x7F040030
			public const int btnLogin = 2130968624;
			
			// aapt resource value: 0x7F040031
			public const int btnMo = 2130968625;
			
			// aapt resource value: 0x7F040032
			public const int btnNewDownload = 2130968626;
			
			// aapt resource value: 0x7F040033
			public const int btnNonCon = 2130968627;
			
			// aapt resource value: 0x7F040034
			public const int btnOk = 2130968628;
			
			// aapt resource value: 0x7F040035
			public const int btnPilot = 2130968629;
			
			// aapt resource value: 0x7F040036
			public const int btnPositionThenLine = 2130968630;
			
			// aapt resource value: 0x7F040037
			public const int btnPrint = 2130968631;
			
			// aapt resource value: 0x7F040038
			public const int btnPurchaseInApp = 2130968632;
			
			// aapt resource value: 0x7F040039
			public const int btnRemove = 2130968633;
			
			// aapt resource value: 0x7F04003A
			public const int btnRes = 2130968634;
			
			// aapt resource value: 0x7F04003B
			public const int btnSa = 2130968635;
			
			// aapt resource value: 0x7F04003C
			public const int btnSave = 2130968636;
			
			// aapt resource value: 0x7F04003D
			public const int btnSeniority = 2130968637;
			
			// aapt resource value: 0x7F04003E
			public const int btnSetCarrier = 2130968638;
			
			// aapt resource value: 0x7F04003F
			public const int btnSinglePay = 2130968639;
			
			// aapt resource value: 0x7F040040
			public const int btnStandardSort = 2130968640;
			
			// aapt resource value: 0x7F040041
			public const int btnStart = 2130968641;
			
			// aapt resource value: 0x7F040042
			public const int btnSu = 2130968642;
			
			// aapt resource value: 0x7F040043
			public const int btnSubmit = 2130968643;
			
			// aapt resource value: 0x7F040044
			public const int btnTh = 2130968644;
			
			// aapt resource value: 0x7F040045
			public const int btnThreeDay = 2130968645;
			
			// aapt resource value: 0x7F040046
			public const int btnToHome = 2130968646;
			
			// aapt resource value: 0x7F040047
			public const int btnToWork = 2130968647;
			
			// aapt resource value: 0x7F040048
			public const int btnTrip = 2130968648;
			
			// aapt resource value: 0x7F040049
			public const int btnTu = 2130968649;
			
			// aapt resource value: 0x7F04004A
			public const int btnTurn = 2130968650;
			
			// aapt resource value: 0x7F04004B
			public const int btnTwoDay = 2130968651;
			
			// aapt resource value: 0x7F04004C
			public const int btnValidSubscription = 2130968652;
			
			// aapt resource value: 0x7F04004D
			public const int btnViewBidReceipt = 2130968653;
			
			// aapt resource value: 0x7F04004E
			public const int btnWe = 2130968654;
			
			// aapt resource value: 0x7F04004F
			public const int edtCellphone = 2130968655;
			
			// aapt resource value: 0x7F040050
			public const int edtEmail = 2130968656;
			
			// aapt resource value: 0x7F040051
			public const int edtEmailConfirm = 2130968657;
			
			// aapt resource value: 0x7F040052
			public const int edtEmployeeNumber = 2130968658;
			
			// aapt resource value: 0x7F040053
			public const int edtFirstAvoid = 2130968659;
			
			// aapt resource value: 0x7F040054
			public const int edtFirstName = 2130968660;
			
			// aapt resource value: 0x7F040055
			public const int edtLastName = 2130968661;
			
			// aapt resource value: 0x7F040056
			public const int edtPassword = 2130968662;
			
			// aapt resource value: 0x7F040057
			public const int edtRePassword = 2130968663;
			
			// aapt resource value: 0x7F040058
			public const int edtSecondAvoid = 2130968664;
			
			// aapt resource value: 0x7F040059
			public const int edtSeniority = 2130968665;
			
			// aapt resource value: 0x7F04005A
			public const int edtThirdAvoid = 2130968666;
			
			// aapt resource value: 0x7F04005B
			public const int edtUserID = 2130968667;
			
			// aapt resource value: 0x7F04005C
			public const int grdCalendar = 2130968668;
			
			// aapt resource value: 0x7F04005D
			public const int grdCityPicker = 2130968669;
			
			// aapt resource value: 0x7F04005E
			public const int imgCmutCityInfo = 2130968670;
			
			// aapt resource value: 0x7F04005F
			public const int imgCmutCityTime = 2130968671;
			
			// aapt resource value: 0x7F040060
			public const int imgPadBackToBaseInfo = 2130968672;
			
			// aapt resource value: 0x7F040061
			public const int imgPadCheckInnfo = 2130968673;
			
			// aapt resource value: 0x7F040062
			public const int imgViewCommuteInfo = 2130968674;
			
			// aapt resource value: 0x7F040063
			public const int lbAppName = 2130968675;
			
			// aapt resource value: 0x7F040064
			public const int lbGoWebsite = 2130968676;
			
			// aapt resource value: 0x7F040065
			public const int lbSubDateExpired = 2130968677;
			
			// aapt resource value: 0x7F040066
			public const int lbSubExpiredOn = 2130968678;
			
			// aapt resource value: 0x7F040067
			public const int lbTitleBase = 2130968679;
			
			// aapt resource value: 0x7F040002
			public const int LeftButton = 2130968578;
			
			// aapt resource value: 0x7F040068
			public const int linearLayout1 = 2130968680;
			
			// aapt resource value: 0x7F040069
			public const int linearLayout2 = 2130968681;
			
			// aapt resource value: 0x7F04006A
			public const int lnAdvanceSort = 2130968682;
			
			// aapt resource value: 0x7F04006B
			public const int lnBottomControl = 2130968683;
			
			// aapt resource value: 0x7F04006C
			public const int lnBottomControll = 2130968684;
			
			// aapt resource value: 0x7F04006D
			public const int lnSingleSort = 2130968685;
			
			// aapt resource value: 0x7F04006E
			public const int lvAuthorizes = 2130968686;
			
			// aapt resource value: 0x7F04006F
			public const int lvBlockSort = 2130968687;
			
			// aapt resource value: 0x7F040070
			public const int lvConstraint = 2130968688;
			
			// aapt resource value: 0x7F040071
			public const int main_content = 2130968689;
			
			// aapt resource value: 0x7F040072
			public const int progress = 2130968690;
			
			// aapt resource value: 0x7F040073
			public const int progressBid = 2130968691;
			
			// aapt resource value: 0x7F040074
			public const int recyclerViewBase = 2130968692;
			
			// aapt resource value: 0x7F040075
			public const int recyclerViewRound = 2130968693;
			
			// aapt resource value: 0x7F040076
			public const int recyclerViewSeat = 2130968694;
			
			// aapt resource value: 0x7F040003
			public const int RightButton = 2130968579;
			
			// aapt resource value: 0x7F040077
			public const int rlAmPmCell = 2130968695;
			
			// aapt resource value: 0x7F040078
			public const int rlBlockSort = 2130968696;
			
			// aapt resource value: 0x7F040079
			public const int rlCmutLineCell = 2130968697;
			
			// aapt resource value: 0x7F04007D
			public const int rlDaysOfMonthCell = 2130968701;
			
			// aapt resource value: 0x7F04007B
			public const int rlDayWeekAllCell = 2130968699;
			
			// aapt resource value: 0x7F04007C
			public const int rlDayWeelSomeCell = 2130968700;
			
			// aapt resource value: 0x7F04007A
			public const int rlDHFirstLastCell = 2130968698;
			
			// aapt resource value: 0x7F04007E
			public const int rlEquipmentCell = 2130968702;
			
			// aapt resource value: 0x7F04007F
			public const int rlLineTypeCell = 2130968703;
			
			// aapt resource value: 0x7F040080
			public const int rlNoConstraint = 2130968704;
			
			// aapt resource value: 0x7F040081
			public const int rlOvernightCityCell = 2130968705;
			
			// aapt resource value: 0x7F040082
			public const int rlRestCell = 2130968706;
			
			// aapt resource value: 0x7F040083
			public const int rlRowBase = 2130968707;
			
			// aapt resource value: 0x7F040084
			public const int rlStartDayWeekCell = 2130968708;
			
			// aapt resource value: 0x7F040085
			public const int rlTripBlockLengthCell = 2130968709;
			
			// aapt resource value: 0x7F040086
			public const int rlViewSort = 2130968710;
			
			// aapt resource value: 0x7F040087
			public const int scrStandardSort = 2130968711;
			
			// aapt resource value: 0x7F040088
			public const int swAddReserve = 2130968712;
			
			// aapt resource value: 0x7F040089
			public const int swBidDown = 2130968713;
			
			// aapt resource value: 0x7F04008A
			public const int switchAdvance = 2130968714;
			
			// aapt resource value: 0x7F04008B
			public const int tile_layout = 2130968715;
			
			// aapt resource value: 0x7F04008C
			public const int tile_text = 2130968716;
			
			// aapt resource value: 0x7F04008D
			public const int tvBidAvoidOne = 2130968717;
			
			// aapt resource value: 0x7F04008E
			public const int tvBidAvoidThree = 2130968718;
			
			// aapt resource value: 0x7F04008F
			public const int tvBidAvoidTwo = 2130968719;
			
			// aapt resource value: 0x7F040090
			public const int tvBidReceiptTitle = 2130968720;
			
			// aapt resource value: 0x7F040091
			public const int tvBidSent = 2130968721;
			
			// aapt resource value: 0x7F040092
			public const int tvBidShowNext = 2130968722;
			
			// aapt resource value: 0x7F040093
			public const int tvBlockTitle = 2130968723;
			
			// aapt resource value: 0x7F040095
			public const int tvCmutCity = 2130968725;
			
			// aapt resource value: 0x7F040096
			public const int tvCmutTime = 2130968726;
			
			// aapt resource value: 0x7F040097
			public const int tvComboCalculate = 2130968727;
			
			// aapt resource value: 0x7F040098
			public const int tvCommuteInfo = 2130968728;
			
			// aapt resource value: 0x7F040094
			public const int tvCWAPsd = 2130968724;
			
			// aapt resource value: 0x7F04009A
			public const int tvDayItem = 2130968730;
			
			// aapt resource value: 0x7F04009B
			public const int tvDayOfMonth = 2130968731;
			
			// aapt resource value: 0x7F04009C
			public const int tvDayOfMonthTitle = 2130968732;
			
			// aapt resource value: 0x7F04009D
			public const int tvDayOfWeek = 2130968733;
			
			// aapt resource value: 0x7F04009E
			public const int tvDayValue = 2130968734;
			
			// aapt resource value: 0x7F040099
			public const int tvDHValue = 2130968729;
			
			// aapt resource value: 0x7F04009F
			public const int tvDoneSetting = 2130968735;
			
			// aapt resource value: 0x7F0400A0
			public const int tvEquipmentTitle = 2130968736;
			
			// aapt resource value: 0x7F0400A1
			public const int tvEquipmentValue = 2130968737;
			
			// aapt resource value: 0x7F0400A2
			public const int tvHowMany = 2130968738;
			
			// aapt resource value: 0x7F0400A3
			public const int tvLicense = 2130968739;
			
			// aapt resource value: 0x7F0400A4
			public const int tvLine = 2130968740;
			
			// aapt resource value: 0x7F0400A5
			public const int tvMessage = 2130968741;
			
			// aapt resource value: 0x7F0400A6
			public const int tvMessageError = 2130968742;
			
			// aapt resource value: 0x7F0400A7
			public const int tvMonthYear = 2130968743;
			
			// aapt resource value: 0x7F0400A8
			public const int tvMoreLess = 2130968744;
			
			// aapt resource value: 0x7F0400A9
			public const int tvMostSortPay = 2130968745;
			
			// aapt resource value: 0x7F0400AA
			public const int tvNoConstraint = 2130968746;
			
			// aapt resource value: 0x7F0400AB
			public const int tvPadBackToBase = 2130968747;
			
			// aapt resource value: 0x7F0400AC
			public const int tvPadCheckIn = 2130968748;
			
			// aapt resource value: 0x7F0400AD
			public const int tvPosition = 2130968749;
			
			// aapt resource value: 0x7F0400AE
			public const int tvPrivacy = 2130968750;
			
			// aapt resource value: 0x7F0400AF
			public const int tvRestValue = 2130968751;
			
			// aapt resource value: 0x7F0400B0
			public const int tvScreenSort = 2130968752;
			
			// aapt resource value: 0x7F0400B1
			public const int tvSenioryCount = 2130968753;
			
			// aapt resource value: 0x7F0400B2
			public const int tvSortSubKey = 2130968754;
			
			// aapt resource value: 0x7F0400B3
			public const int tvSubmital = 2130968755;
			
			// aapt resource value: 0x7F0400B4
			public const int tvTitle1st = 2130968756;
			
			// aapt resource value: 0x7F0400B5
			public const int tvTitle2nd = 2130968757;
			
			// aapt resource value: 0x7F0400B6
			public const int tvTitle3rd = 2130968758;
			
			// aapt resource value: 0x7F0400B7
			public const int tvTitle4th = 2130968759;
			
			// aapt resource value: 0x7F0400B8
			public const int tvTitleCalculate = 2130968760;
			
			// aapt resource value: 0x7F0400B9
			public const int tvTitleChoices = 2130968761;
			
			// aapt resource value: 0x7F0400BA
			public const int tvTitleCorrect = 2130968762;
			
			// aapt resource value: 0x7F0400BB
			public const int tvTitleLogin = 2130968763;
			
			// aapt resource value: 0x7F0400BC
			public const int tvTitleLoginSubmit = 2130968764;
			
			// aapt resource value: 0x7F0400BD
			public const int tvTitlePosition = 2130968765;
			
			// aapt resource value: 0x7F0400BE
			public const int tvTitlePriority = 2130968766;
			
			// aapt resource value: 0x7F0400BF
			public const int tvTitleScreen = 2130968767;
			
			// aapt resource value: 0x7F0400C0
			public const int tvTitleSubSort = 2130968768;
			
			// aapt resource value: 0x7F0400C1
			public const int tvTitleUsePsd = 2130968769;
			
			// aapt resource value: 0x7F0400C2
			public const int tvUserId = 2130968770;
			
			// aapt resource value: 0x7F0400C3
			public const int tvValue = 2130968771;
			
			// aapt resource value: 0x7F0400C4
			public const int tvViewCmut = 2130968772;
			
			// aapt resource value: 0x7F0400C5
			public const int tvViewCommuteTime = 2130968773;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int BidToolbar = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int CellAmPm = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int CellCommutableLines = 2131034114;
			
			// aapt resource value: 0x7F050004
			public const int CellDayOfMonth = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int CellDayWeekAll = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int CellDayWeekSome = 2131034118;
			
			// aapt resource value: 0x7F050003
			public const int CellDHFirstLast = 2131034115;
			
			// aapt resource value: 0x7F050007
			public const int CellEquipment = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int CellLineType = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int CellOvernightCity = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int CellRest = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int CellStartDayWeek = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int CellTripBlockLength = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int Cell_Block_Sort = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int CityItem = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int DayItem = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int DialogAuthorizeServices = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int DialogConstraints = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int DialogMessage = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int ExpiredSubscription = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int Home = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int LayoutAuthorizeServices = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int LayoutAuthorizeStatus = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int LayoutBidReceiptView = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int LayoutBlockSort = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int LayoutCalculateBidView = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int LayoutCitiesView = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int LayoutCommuteInformation = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public const int LayoutConstraintView = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int LayoutCreateAccount = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public const int LayoutDayOfMonth = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int LayoutEmailSentView = 2131034143;
			
			// aapt resource value: 0x7F050020
			public const int LayoutLoginSubmitView = 2131034144;
			
			// aapt resource value: 0x7F050021
			public const int LayoutLoginView = 2131034145;
			
			// aapt resource value: 0x7F050022
			public const int LayoutPickerCity = 2131034146;
			
			// aapt resource value: 0x7F050023
			public const int LayoutSeatAndRound = 2131034147;
			
			// aapt resource value: 0x7F050024
			public const int LayoutSingleSort = 2131034148;
			
			// aapt resource value: 0x7F050025
			public const int LayoutSortView = 2131034149;
			
			// aapt resource value: 0x7F050027
			public const int LayoutSubmitalChoices = 2131034151;
			
			// aapt resource value: 0x7F050028
			public const int LayoutSubmitalPosition = 2131034152;
			
			// aapt resource value: 0x7F050029
			public const int LayoutSubmitalPriority = 2131034153;
			
			// aapt resource value: 0x7F050026
			public const int LayoutSubSortView = 2131034150;
			
			// aapt resource value: 0x7F05002A
			public const int Main = 2131034154;
			
			// aapt resource value: 0x7F05002B
			public const int RowConstraint = 2131034155;
			
			// aapt resource value: 0x7F05002E
			public const int row_select_author = 2131034158;
			
			// aapt resource value: 0x7F05002F
			public const int row_select_base = 2131034159;
			
			// aapt resource value: 0x7F05002C
			public const int SelectBase = 2131034156;
			
			// aapt resource value: 0x7F05002D
			public const int SplashScreen = 2131034157;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7F060000
			public const int BidHeader = 2131099648;
			
			// aapt resource value: 0x7F060002
			public const int bid_name = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int button_add_reserve = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int button_advanced = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int button_all = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int button_am_pm = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int button_back = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int button_bid_down = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int button_block_pay_dutty = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int button_block_sort = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int button_calculate = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int button_calculate_bid = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int button_cancel = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int button_clear = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int button_clear_all = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int button_continue = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int button_create = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int button_days_off = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int button_delete = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int button_done = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int button_edit_user_account = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int button_email = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int button_expired_month = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int button_expired_subscription = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int button_fitart = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int button_line_then_position = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int button_login = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int button_login_submit = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int button_new_download = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public const int button_pay = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int button_pay_block = 2131099679;
			
			// aapt resource value: 0x7F060020
			public const int button_pay_day = 2131099680;
			
			// aapt resource value: 0x7F060021
			public const int button_pay_dutty = 2131099681;
			
			// aapt resource value: 0x7F060022
			public const int button_pay_fdp = 2131099682;
			
			// aapt resource value: 0x7F060023
			public const int button_pay_tafb = 2131099683;
			
			// aapt resource value: 0x7F060024
			public const int button_per_diem = 2131099684;
			
			// aapt resource value: 0x7F060025
			public const int button_pilot = 2131099685;
			
			// aapt resource value: 0x7F060026
			public const int button_pm_am = 2131099686;
			
			// aapt resource value: 0x7F060027
			public const int button_position_then_line = 2131099687;
			
			// aapt resource value: 0x7F060028
			public const int button_print = 2131099688;
			
			// aapt resource value: 0x7F060029
			public const int button_purchase = 2131099689;
			
			// aapt resource value: 0x7F06002A
			public const int button_save_change = 2131099690;
			
			// aapt resource value: 0x7F06002B
			public const int button_seniority = 2131099691;
			
			// aapt resource value: 0x7F06002C
			public const int button_setcarrier = 2131099692;
			
			// aapt resource value: 0x7F06002D
			public const int button_some = 2131099693;
			
			// aapt resource value: 0x7F06002E
			public const int button_standard_sort = 2131099694;
			
			// aapt resource value: 0x7F06002F
			public const int button_start = 2131099695;
			
			// aapt resource value: 0x7F060030
			public const int button_submit_bid = 2131099696;
			
			// aapt resource value: 0x7F060031
			public const int button_vac_pay = 2131099697;
			
			// aapt resource value: 0x7F060032
			public const int button_valid_subscription = 2131099698;
			
			// aapt resource value: 0x7F060033
			public const int button_view_bid_receipt = 2131099699;
			
			// aapt resource value: 0x7F060034
			public const int button_weekday = 2131099700;
			
			// aapt resource value: 0x7F060035
			public const int input_cwa_password = 2131099701;
			
			// aapt resource value: 0x7F060036
			public const int input_emp_number = 2131099702;
			
			// aapt resource value: 0x7F060037
			public const int input_password = 2131099703;
			
			// aapt resource value: 0x7F060038
			public const int input_username = 2131099704;
			
			// aapt resource value: 0x7F060039
			public const int label_accept_email = 2131099705;
			
			// aapt resource value: 0x7F06003A
			public const int label_accept_term = 2131099706;
			
			// aapt resource value: 0x7F06003B
			public const int label_author_msg = 2131099707;
			
			// aapt resource value: 0x7F06003C
			public const int label_bid_avoid_one = 2131099708;
			
			// aapt resource value: 0x7F06003D
			public const int label_bid_avoid_three = 2131099709;
			
			// aapt resource value: 0x7F06003E
			public const int label_bid_avoid_two = 2131099710;
			
			// aapt resource value: 0x7F06003F
			public const int label_bid_hint = 2131099711;
			
			// aapt resource value: 0x7F060040
			public const int label_bid_position_piority = 2131099712;
			
			// aapt resource value: 0x7F060041
			public const int label_bid_receipt = 2131099713;
			
			// aapt resource value: 0x7F060042
			public const int label_bid_show_next = 2131099714;
			
			// aapt resource value: 0x7F060043
			public const int label_calculating_bid = 2131099715;
			
			// aapt resource value: 0x7F060044
			public const int label_calculating_combo = 2131099716;
			
			// aapt resource value: 0x7F060045
			public const int label_cellcarrier = 2131099717;
			
			// aapt resource value: 0x7F060046
			public const int label_cellphone = 2131099718;
			
			// aapt resource value: 0x7F060047
			public const int label_correct_title = 2131099719;
			
			// aapt resource value: 0x7F060048
			public const int label_date_expires = 2131099720;
			
			// aapt resource value: 0x7F060049
			public const int label_email = 2131099721;
			
			// aapt resource value: 0x7F06004A
			public const int label_email_confirm = 2131099722;
			
			// aapt resource value: 0x7F06004B
			public const int label_email_sent = 2131099723;
			
			// aapt resource value: 0x7F06004C
			public const int label_employee_number = 2131099724;
			
			// aapt resource value: 0x7F06004D
			public const int label_enter_bid_avoidance = 2131099725;
			
			// aapt resource value: 0x7F06004E
			public const int label_enter_credentials = 2131099726;
			
			// aapt resource value: 0x7F06004F
			public const int label_first_name = 2131099727;
			
			// aapt resource value: 0x7F060050
			public const int label_goto_subscription = 2131099728;
			
			// aapt resource value: 0x7F060051
			public const int label_high_piority = 2131099729;
			
			// aapt resource value: 0x7F060052
			public const int label_last_name = 2131099730;
			
			// aapt resource value: 0x7F060053
			public const int label_license = 2131099731;
			
			// aapt resource value: 0x7F060054
			public const int label_line_position = 2131099732;
			
			// aapt resource value: 0x7F060055
			public const int label_login_hint = 2131099733;
			
			// aapt resource value: 0x7F060056
			public const int label_more_information = 2131099734;
			
			// aapt resource value: 0x7F060057
			public const int label_order_sort_key = 2131099735;
			
			// aapt resource value: 0x7F060058
			public const int label_password = 2131099736;
			
			// aapt resource value: 0x7F060059
			public const int label_position = 2131099737;
			
			// aapt resource value: 0x7F06005A
			public const int label_position_line = 2131099738;
			
			// aapt resource value: 0x7F06005B
			public const int label_privacy = 2131099739;
			
			// aapt resource value: 0x7F06005C
			public const int label_repassword = 2131099740;
			
			// aapt resource value: 0x7F06005D
			public const int label_select_base = 2131099741;
			
			// aapt resource value: 0x7F06005E
			public const int label_select_round = 2131099742;
			
			// aapt resource value: 0x7F06005F
			public const int label_select_seat = 2131099743;
			
			// aapt resource value: 0x7F060060
			public const int label_single_standard_sort = 2131099744;
			
			// aapt resource value: 0x7F060061
			public const int label_start_state = 2131099745;
			
			// aapt resource value: 0x7F060065
			public const int label_submital_choices = 2131099749;
			
			// aapt resource value: 0x7F060064
			public const int label_submit_title = 2131099748;
			
			// aapt resource value: 0x7F060066
			public const int label_subscription_expired = 2131099750;
			
			// aapt resource value: 0x7F060067
			public const int label_subscription_expires = 2131099751;
			
			// aapt resource value: 0x7F060068
			public const int label_subscription_single_month = 2131099752;
			
			// aapt resource value: 0x7F060062
			public const int label_sub_block_sort_title = 2131099746;
			
			// aapt resource value: 0x7F060063
			public const int label_sub_single_sort_title = 2131099747;
			
			// aapt resource value: 0x7F060069
			public const int label_title_block_sort = 2131099753;
			
			// aapt resource value: 0x7F06006A
			public const int label_title_create_account = 2131099754;
			
			// aapt resource value: 0x7F06006B
			public const int label_title_edit_account = 2131099755;
			
			// aapt resource value: 0x7F06006C
			public const int label_title_home = 2131099756;
			
			// aapt resource value: 0x7F06006D
			public const int label_title_single_sort = 2131099757;
			
			// aapt resource value: 0x7F06006E
			public const int label_user_id = 2131099758;
			
			// aapt resource value: 0x7F06006F
			public const int label_your_seniority = 2131099759;
			
			// aapt resource value: 0x7F060070
			public const int space = 2131099760;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int BidButton = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int BidButton_Cancel = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int BidButton_CellConstraint = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int BidButton_Create = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int BidButton_Sort = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int BidCommutButton = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int BidCommutButton_Info = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int BidDeleteButton = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int BidFillableLayout = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int BidHeader = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int BidInputText = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int BidInputText_CreateAccount = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int BidNumberLayout = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int BidSmallCircle = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int BidText = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int BidText_CellConstraint = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int BidText_CellSmall = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int BidText_CreateAccount = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int BidTheme_Base = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int BidTheme_Splash = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int Bid_Theme = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int Bid_ThemeTitle = 2131165205;
			
			// aapt resource value: 0x7F070016
			public const int Button = 2131165206;
			
			// aapt resource value: 0x7F070017
			public const int Button_StartState = 2131165207;
			
			// aapt resource value: 0x7F070018
			public const int Button_Submital = 2131165208;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
