// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Bidvalet.iOS
{
	public partial class HistoryBidDomicilesCell : UICollectionViewCell
	{
		public HistoryBidDomicilesCell (IntPtr handle) : base (handle)
		{
		}
	}
}
