// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Bidvalet.iOS
{
	public partial class SelectHistoryViewController : UIViewController
	{
		public SelectHistoryViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
