// This file has been autogenerated from a class added in the UI designer.
#region NameSpace

using System;
using Foundation;
using UIKit; 
#endregion

namespace Bidvalet.iOS
{
	public partial class SelectBaseViewController : BaseViewController
	{
		public SelectBaseViewController (IntPtr handle) : base (handle)
		{		
		}

        #region Events
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            ShowNavigationBar();
            Title = "Select Base";
            tvBase.Source = new BaseDateSource(Constants.SelectBase, this);
            tvBase.TableFooterView = new UIView();
        }

        public void RowSelected(string cellName)
        {
            if (GlobalSettings.UserInfo != null)
            {
                GlobalSettings.UserInfo.Domicile = cellName;
            }
            GlobalSettings.Domicile = cellName;
            // push new viewcontroller
            //Console.WriteLine(cellName);
            SelectSeatAndRoundViewController selectSeatAndRoundViewController = Storyboard.InstantiateViewController("SelectSeatAndRoundViewController") as SelectSeatAndRoundViewController;
            selectSeatAndRoundViewController.baseSelected = cellName;
            PushViewController(selectSeatAndRoundViewController, true);
        }
        
        #endregion

	}
}
